title: Multigroup Events
display_name: Multigroup Events
min_age: 
max_age: 
omniauth_providers: ['meetup', 'twitter', 'facebook', 'google_apps']
omniauth_providers_with_key: ['meetup', 'twitter', 'facebook']
remote_api_sources:
  meetup:
    name: 'meetup'
    uri_host: 'api.meetup.com'
  facebook:
    name: 'facebook'
    uri_host: 'api.facebook.com'
user_form_options: ['name?', 'username?', 'gender?', 'birthdate?', 'time_zone?', 'country?', 'zip_code?', 'geo_area?']
valid_event_js_templates: ['event', 'event_list', 'no_rsvp', 'rsvp_count', 'rsvp_list', 'yes_rsvp', 'num_yes_rsvps_by_event', 'my_events_chooser']
enable_name?: true
require_name?: true
enable_username?: true
require_username?: true
enable_gender?: false
require_gender?: false
enable_birthdate?: false
require_birthdate?: false
enable_time_zone?: false
require_time_zone?: false
enable_country?: false
require_country?: false
enable_zip_code?: false
require_zip_code?: false
enable_geo_area?: false
require_geo_area?: fasle
verify_email?: true
user_name_field: email
use_friendly_name_id?: true
user_identity_field: username
check_remember_me?: true
use_avatar_gender_default?: true
password_reset_ttl_hours: 4
original_avatar_size: [400, 400]
large_avatar_size: [200, 200]
medium_avatar_size: [100, 100]
small_avatar_size: [60, 60]
tiny__avatar_size: [30, 30]
default_country: US
default_time_zone: "Eastern Time (US & Canada)"
default_remember_me: false
development:
  host: "localhost:3000"
test:
  host: "test.local"
production:
  host: "www.ApplicationTemplate.com"