--- 
- !ruby/object:EventType
  name: Event
  title: Regular Event
  tag: event
  is_default: true
  is_remote: false
  rank: 1 
  description: >
    This is a normal event with no external dependencies.
- !ruby/object:EventType
  name: RemoteEvent
  title: Remote Event
  tag: remote
  is_default: false
  is_remote: true
  rank: 2
  description: >
    This is an event that has multiple remote events
    (currently only from Meetup) attatched to it. The
    event info can be populated from the primary remote
    event and the RSVP's from all attatched events will
    be combined and deduped into one list.


